// Mocks generated by Mockito 5.4.6 from annotations
// in pillpilot/test/controllers/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pillpilot/models/appointment_model.dart' as _i3;
import 'package:pillpilot/models/medication_model.dart' as _i2;
import 'package:pillpilot/services/appointment_service.dart' as _i7;
import 'package:pillpilot/services/medication_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMedication_0 extends _i1.SmartFake implements _i2.Medication {
  _FakeMedication_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppointment_1 extends _i1.SmartFake implements _i3.Appointment {
  _FakeAppointment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MedicationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationService extends _i1.Mock implements _i4.MedicationService {
  MockMedicationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Medication>> getMedications() =>
      (super.noSuchMethod(
            Invocation.method(#getMedications, []),
            returnValue: _i5.Future<List<_i2.Medication>>.value(
              <_i2.Medication>[],
            ),
          )
          as _i5.Future<List<_i2.Medication>>);

  @override
  _i5.Future<_i2.Medication> getMedicationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMedicationById, [id]),
            returnValue: _i5.Future<_i2.Medication>.value(
              _FakeMedication_0(
                this,
                Invocation.method(#getMedicationById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.Medication>);

  @override
  _i5.Future<_i2.Medication> createMedication(
    String? name,
    String? dosage,
    _i6.TimeOfDay? time,
    List<int>? daysOfWeek, {
    String? notes = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createMedication,
              [name, dosage, time, daysOfWeek],
              {#notes: notes},
            ),
            returnValue: _i5.Future<_i2.Medication>.value(
              _FakeMedication_0(
                this,
                Invocation.method(
                  #createMedication,
                  [name, dosage, time, daysOfWeek],
                  {#notes: notes},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Medication>);

  @override
  _i5.Future<_i2.Medication> updateMedication(_i2.Medication? medication) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedication, [medication]),
            returnValue: _i5.Future<_i2.Medication>.value(
              _FakeMedication_0(
                this,
                Invocation.method(#updateMedication, [medication]),
              ),
            ),
          )
          as _i5.Future<_i2.Medication>);

  @override
  _i5.Future<void> deleteMedication(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedication, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AppointmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentService extends _i1.Mock
    implements _i7.AppointmentService {
  MockAppointmentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Appointment>> getAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getAppointments, []),
            returnValue: _i5.Future<List<_i3.Appointment>>.value(
              <_i3.Appointment>[],
            ),
          )
          as _i5.Future<List<_i3.Appointment>>);

  @override
  _i5.Future<_i3.Appointment> getAppointmentById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentById, [id]),
            returnValue: _i5.Future<_i3.Appointment>.value(
              _FakeAppointment_1(
                this,
                Invocation.method(#getAppointmentById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.Appointment>);

  @override
  _i5.Future<_i3.Appointment> createAppointment(
    String? title,
    DateTime? date,
    _i6.TimeOfDay? time, {
    String? notes = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createAppointment,
              [title, date, time],
              {#notes: notes},
            ),
            returnValue: _i5.Future<_i3.Appointment>.value(
              _FakeAppointment_1(
                this,
                Invocation.method(
                  #createAppointment,
                  [title, date, time],
                  {#notes: notes},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Appointment>);

  @override
  _i5.Future<_i3.Appointment> updateAppointment(_i3.Appointment? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [appointment]),
            returnValue: _i5.Future<_i3.Appointment>.value(
              _FakeAppointment_1(
                this,
                Invocation.method(#updateAppointment, [appointment]),
              ),
            ),
          )
          as _i5.Future<_i3.Appointment>);

  @override
  _i5.Future<void> deleteAppointment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppointment, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Appointment>> getAppointmentsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsForDate, [date]),
            returnValue: _i5.Future<List<_i3.Appointment>>.value(
              <_i3.Appointment>[],
            ),
          )
          as _i5.Future<List<_i3.Appointment>>);

  @override
  _i5.Future<List<DateTime>> getDatesWithAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getDatesWithAppointments, []),
            returnValue: _i5.Future<List<DateTime>>.value(<DateTime>[]),
          )
          as _i5.Future<List<DateTime>>);
}
